export const existingGamesList: Array<{ name: string; url: string }> = [
  { name: 'Heroes Assemble', url: 'https://www.crazygames.com/embed/heroes-assemble' },
  { name: 'Poxel-io', url: 'https://www.crazygames.com/embed/poxel-io' },
  { name: 'Bitcoiner', url: 'https://www.crazygames.com/embed/bitcoiner' },
  { name: 'Papas Wingeria', url: 'https://www.crazygames.com/embed/papas-wingeria' },
  { name: 'The Farmer', url: 'https://www.crazygames.com/embed/idle-farming-business' },
  { name: 'Among Us', url: 'https://www.crazygames.com/embed/among-us-online-edition' },
  { name: 'Tetris', url: 'https://www.crazygames.com/embed/tetris' },
  { name: 'Subway Surfers', url: 'https://www.crazygames.com/embed/subway-surfers' },
  { name: '2048', url: 'https://www.crazygames.com/embed/2048' },
  { name: 'Chess', url: 'https://www.crazygames.com/embed/chess' },
  { name: 'Smash Karts', url: 'https://www.crazygames.com/embed/smash-karts' },
  { name: 'Krunker-io', url: 'https://www.crazygames.com/embed/krunker-io' },
  { name: 'Shell Shockers', url: 'https://www.crazygames.com/embed/shell-shockers' },
  { name: 'Slope Tunnel', url: 'https://www.crazygames.com/embed/slope-tunnel' },
  { name: 'Crossy Road', url: 'https://www.crazygames.com/embed/crossy-road' },
  { name: 'Snake', url: 'https://www.crazygames.com/embed/snake' },
  { name: 'Bubble Shooter', url: 'https://www.crazygames.com/embed/bubble-shooter' },
  { name: 'Run 3', url: 'https://www.crazygames.com/embed/run-3' },
  { name: 'Geometry Dash', url: 'https://www.crazygames.com/embed/geometry-dash' },
  { name: 'Moto X3M', url: 'https://www.crazygames.com/embed/moto-x3m' },
]
