export const existingGamesList: Array<{ name: string; url: string }> = [
  { name: 'Heroes Assemble', url: 'https://www.crazygames.com/embed/heroes-assemble' },
  { name: 'Poxel-io', url: 'https://www.crazygames.com/embed/poxel-io' },
  { name: 'Bitcoiner', url: 'https://www.crazygames.com/embed/bitcoiner' },
  { name: 'Papas Wingeria', url: 'https://www.crazygames.com/embed/papas-wingeria' },
  { name: 'The Farmer', url: 'https://www.crazygames.com/embed/idle-farming-business' },
  { name: 'Jacksmith', url: 'https://www.crazygames.com/embed/jacksmith' },
  { name: 'Magic Kingdom Hex Match', url: 'https://www.crazygames.com/embed/hexa-sort' },
  { name: 'Mini Mine', url: 'https://www.crazygames.com/embed/mining-rush' },
  { name: 'Art of Alchemy Merge Elements', url: 'https://www.crazygames.com/embed/little-alchemy-2' },
  { name: 'Idle Ants', url: 'https://www.crazygames.com/embed/idle-ants' },
  { name: '100 Meters Race', url: 'https://www.crazygames.com/embed/100-meters-race' },
  { name: 'Neon Planet Idle Clicker', url: 'https://www.crazygames.com/embed/planet-clicker-2' },
  { name: 'Ragdoll Archers', url: 'https://www.crazygames.com/embed/ragdoll-archers' },
  { name: 'Skydom', url: 'https://www.crazygames.com/embed/skydom' },
  { name: 'Slice Master', url: 'https://www.crazygames.com/embed/slice-master' },
  { name: 'Pixel Warfare', url: 'https://www.crazygames.com/embed/pixel-warfare' },
  { name: 'Thief Puzzle', url: 'https://www.crazygames.com/embed/thief-puzzle' },
  { name: '8 Ball Billiards Classic', url: 'https://www.crazygames.com/embed/8-ball-billiards-classic' },
  { name: 'Draw Climber', url: 'https://www.crazygames.com/embed/draw-climber' },
  { name: 'Cuberealm-io', url: 'https://www.crazygames.com/embed/cuberealm-io' },
  { name: 'Skillwarz', url: 'https://www.crazygames.com/embed/skillwarz' },
  { name: 'Guess Their Answer', url: 'https://www.crazygames.com/embed/guess-their-answer' },
  { name: 'Space Waves', url: 'https://www.crazygames.com/embed/space-waves' },
  { name: 'Bloxd-IO', url: 'https://www.crazygames.com/embed/bloxdhop-io' },
  { name: 'Spearfishing', url: 'https://www.crazygames.com/embed/spearfishing' },
  { name: 'Night Club Security', url: 'https://www.crazygames.com/embed/night-club-security' },
  { name: 'Real Fishing Simulator', url: 'https://www.crazygames.com/embed/real-fishing-simulator' },
  { name: 'Used Car Dealer Tycoon', url: 'https://www.crazygames.com/embed/used-car-dealer-tycoon' },
  { name: 'The Worlds Easyest Game', url: 'https://www.crazygames.com/embed/the-world-s-easyest-game' },
  { name: 'Ice Fishing', url: 'https://www.crazygames.com/embed/ice-fishing' },
  { name: 'Emoji Puzzle', url: 'https://www.crazygames.com/embed/emoji-puzzle' },
  { name: 'Venge.io', url: 'https://www.crazygames.com/embed/venge-io' },
  { name: 'Murder', url: 'https://www.crazygames.com/embed/murder' },
  { name: 'Rocket Bot Royale', url: 'https://www.crazygames.com/embed/rocket-bot-royale' },
  { name: 'Boxing Random', url: 'https://www.crazygames.com/embed/boxing-random' },
  { name: 'Sharkosaurus Rampage', url: 'https://www.crazygames.com/embed/sharkosaurus-rampage' },
  { name: 'BuildNow GG', url: 'https://www.crazygames.com/embed/buildnow-gg' },
  { name: 'Rooftop Snipers', url: 'https://www.crazygames.com/embed/rooftop-snipers' },
  { name: 'Stickman Parkour Skyland', url: 'https://www.crazygames.com/embed/stickman-parkour-skyland' },
  { name: 'Big Tower Tiny Square', url: 'https://www.crazygames.com/embed/big-tower-tiny-square' },
  { name: 'Doodle Jump', url: 'https://www.crazygames.com/embed/doodle-jump' },
  { name: 'Stick Fighter', url: 'https://www.crazygames.com/embed/stick-fighter' },
  { name: 'Car Simulator Arena', url: 'https://www.crazygames.com/embed/car-simulator-arena' },
  { name: 'Temple of Boom', url: 'https://www.crazygames.com/embed/temple-of-boom' },
  { name: 'Penalty Shooters 2', url: 'https://www.crazygames.com/embed/penalty-shooters-2' },
  { name: 'Bomber Friends', url: 'https://www.crazygames.com/embed/bomber-friends' },
  { name: 'Crazy Pixel Apocalypse', url: 'https://www.crazygames.com/embed/crazy-pixel-apocalypse' },
  { name: 'Deadshot.io', url: 'https://www.crazygames.com/embed/deadshot-io' },
  { name: 'Bodycamera Shooter', url: 'https://www.crazygames.com/embed/bodycamera-shooter' },
  { name: 'Time Shooter 2', url: 'https://www.crazygames.com/embed/time-shooter-2' },
  { name: 'Pixel Gun 3D', url: 'https://www.crazygames.com/embed/pixel-gun-3d' },
  { name: 'Taming.io', url: 'https://www.crazygames.com/embed/taming-io' },
  { name: 'Worm Hunt', url: 'https://www.crazygames.com/embed/worm-hunt' },
  { name: 'Polytrack', url: 'https://www.crazygames.com/embed/polytrack' },
  { name: 'Racing in City', url: 'https://www.crazygames.com/embed/racing-in-city' },
  { name: 'Night City Racing', url: 'https://www.crazygames.com/embed/night-city-racing' },
  { name: 'Rally Racer Dirt', url: 'https://www.crazygames.com/embed/rally-racer-dirt' },
  { name: 'MX Offroad Master', url: 'https://www.crazygames.com/embed/mx-offroad-master' },
  { name: 'Super Star Car', url: 'https://www.crazygames.com/embed/super-star-car' },
  { name: 'Sky Riders', url: 'https://www.crazygames.com/embed/sky-riders' },
  { name: 'The Impossible Quiz', url: 'https://www.crazygames.com/embed/the-impossible-quiz' },
  { name: 'Escape or Die', url: 'https://www.crazygames.com/embed/escape-or-die' },
  { name: 'Puzzle Room Escape', url: 'https://www.crazygames.com/embed/puzzle-room-escape' },
  { name: 'Daily Room Escape', url: 'https://www.crazygames.com/embed/daily-room-escape' },
  { name: 'Paint Room Escape', url: 'https://www.crazygames.com/embed/paint-room-escape' },
  { name: 'Gridpunk - 3v3 Battle Royale', url: 'https://www.crazygames.com/embed/gridpunk---3v3-battle-royale' },
  { name: 'Fall Beans', url: 'https://www.crazygames.com/embed/fall-beans' },
  { name: 'Fleeing the Complex', url: 'https://www.crazygames.com/embed/fleeing-the-complex' },
  { name: 'Skribbl.io', url: 'https://www.crazygames.com/embed/skribblio' },
  { name: 'Wormate.io', url: 'https://www.crazygames.com/embed/wormateio' },
  { name: 'Geometry Dash Online', url: 'https://www.crazygames.com/embed/geometry-dash-online' },
  { name: 'Geometry Neon Dash Subzero', url: 'https://www.crazygames.com/embed/geometry-neon-dash-subzero' },
  { name: 'Bloxorz', url: 'https://www.crazygames.com/embed/bloxorz' },
  { name: 'Duck Life', url: 'https://www.crazygames.com/embed/ducklife' },
  { name: 'Duck Life 2', url: 'https://www.crazygames.com/embed/ducklife-2' },
  { name: 'Duck Life Space', url: 'https://www.crazygames.com/embed/duck-life-space' },
  { name: 'Ducklings', url: 'https://www.crazygames.com/embed/ducklings' },
  { name: 'Slope Tunnel', url: 'https://www.crazygames.com/embed/slope-tunnel' },
  { name: 'Color Tunnel', url: 'https://www.crazygames.com/embed/color-tunnel' },
  { name: 'BasketBros', url: 'https://www.crazygames.com/embed/basketbros' },
  { name: 'Mine Clone', url: 'https://www.crazygames.com/embed/mine-clone' },
  { name: 'Cookie Clicker', url: 'https://www.crazygames.com/embed/cookie-clicker' },
  { name: 'Clicker Heroes', url: 'https://www.crazygames.com/embed/clicker-heroes' },
  { name: "Papa's Freezeria", url: 'https://www.crazygames.com/embed/papas-freezeria' },
  { name: "Papa's Taco Mia", url: 'https://www.crazygames.com/embed/papas-taco-mia' },
  { name: 'Google Feud', url: 'https://www.crazygames.com/embed/google-feud' },
  { name: 'Snake', url: 'https://www.mathsisfun.com/games/snake.html' },
  { name: 'Minesweeper', url: 'https://www.crazygames.com/embed/minesweeper' },
  { name: 'Basketball Stars', url: 'https://www.crazygames.com/embed/basketball-stars' },
  { name: 'Run 3', url: 'https://www.crazygames.com/embed/run-3' },
  { name: 'Chess', url: 'https://www.mathsisfun.com/games/chess.html' },
  { name: 'Whooo?', url: 'https://www.crazygames.com/embed/whooo' },
]
