export const newGamesList: Array<{ name: string; url: string }> = [
  { name: 'Asmr-Girl-Livestream-Mukbang', url: 'https://games.crazygames.com/en_US/asmr-girl-livestream-mukbang/index.html?v=1.347' },
  { name: 'Corn Tycoon', url: 'https://games.crazygames.com/en_US/corn-tycoon/index.html?v=1.347' },
  { name: 'Money Factory', url: 'https://games.crazygames.com/en_US/money-factory-aqs/index.html?v=1.347' },
  { name: 'Pop Jewels', url: 'https://games.crazygames.com/en_US/pop-jewels/index.html?v=1.347' },
  { name: 'Find the Pets', url: 'https://games.crazygames.com/en_US/find-the-pets-cph/index.html?v=1.347' },
  { name: 'Runic Curse', url: 'https://games.crazygames.com/en_US/runic-curse/index.html?v=1.347' },
  { name: 'Pocketro', url: 'https://games.crazygames.com/en_US/pocketro/index.html?v=1.347' },
  { name: 'Big Tower Tiny Square 2', url: 'https://games.crazygames.com/en_US/big-tower-tiny-square-2/index.html?v=1.347' },
  { name: 'Aim Master', url: 'https://games.crazygames.com/en_US/aim-master/index.html?v=1.347' },
  { name: 'Diner in the Storm', url: 'https://games.crazygames.com/en_US/diner-in-the-storm/index.html?v=1.347' },
  { name: 'Foono Online Multiplayer', url: 'https://games.crazygames.com/en_US/foono-online-multiplayer-card-game/index.html?v=1.347' },
  { name: 'Bounce Blocku Golf', url: 'https://games.crazygames.com/en_US/bounce-blocku-golf/index.html?v=1.347' },
  { name: 'Blade Merge', url: 'https://games.crazygames.com/en_US/blade-merge/index.html?v=1.347' },
  { name: 'My Chicken Farm', url: 'https://games.crazygames.com/en_US/my-chicken-farm/index.html?v=1.347' },
  { name: 'Chibi Doll Dress Up Coloring', url: 'https://games.crazygames.com/en_US/chibi-doll-dress-up-coloring/index.html?v=1.347' },
  { name: 'Piles of Mahjong', url: 'https://games.crazygames.com/en_US/piles-of-mahjong-jhb/index.html?v=1.347' },
  { name: 'Tower Swap', url: 'https://games.crazygames.com/en_US/tower-swap/index.html?v=1.347' },
  { name: 'Mahjongg Solitaire', url: 'https://games.crazygames.com/en_US/mahjongg-solitaire/index.html?v=1.347' },
  { name: "Arkadium's Bubble Shooter", url: 'https://games.crazygames.com/en_US/arkadium-s-bubble-shooter/index.html?v=1.347' },
  { name: 'Bubble Blast', url: 'https://games.crazygames.com/en_US/bubble-blast-pwd/index.html?v=1.347' },
  { name: 'Smash Karts', url: 'https://games.crazygames.com/en_US/smash-karts/index.html?v=1.347' },
  { name: 'Skydom Reforged', url: 'https://games.crazygames.com/en_US/skydom-reforged/index.html?v=1.347' },
  { name: 'Farm Merge Valley', url: 'https://games.crazygames.com/en_US/farm-merge-valley/index.html?v=1.347' },
  { name: 'Count Masters Stickman Games', url: 'https://games.crazygames.com/en_US/count-masters-stickman-games/index.html?v=1.347' },
  { name: 'Nuts Puzzle Sort by Color', url: 'https://games.crazygames.com/en_US/nuts-puzzle-sort-by-color/index.html?v=1.347' },
  { name: 'Obby Gym Simulator Escape', url: 'https://games.crazygames.com/en_US/obby-gym-simulator-escape/index.html?v=1.347' },
  { name: 'Tap 3d Wood Block Away', url: 'https://games.crazygames.com/en_US/tap-3d-wood-block-away/index.html?v=1.347' },
  { name: 'Evowars-io', url: 'https://games.crazygames.com/en_US/evowarsio/index.html?v=1.347' },
  { name: 'Fortzone Battle Royale', url: 'https://games.crazygames.com/en_US/fortzone-battle-royale-xkd/index.html?v=1.347' },
  { name: 'Grow a Garden', url: 'https://games.crazygames.com/en_US/grow-a-garden---growden-io/index.html?v=1.347' },
  { name: 'Escape From Prison Multiplayer', url: 'https://games.crazygames.com/en_US/escape-from-prison-multiplayer/index.html?v=1.347' },
  { name: 'Bricks Breaker', url: 'https://games.crazygames.com/en_US/bricks-breaker/index.html?v=1.347' },
  { name: 'Traffic Loop', url: 'https://games.crazygames.com/en_US/traffic-loop/index.html?v=1.347' },
  { name: 'Krunker.io', url: 'https://games.crazygames.com/en_US/krunker-io/index.html?v=1.347' },
  { name: 'Getaway Shootout', url: 'https://games.crazygames.com/en_US/getaway-shootout/index.html?v=1.347' },
  { name: 'Narrow.One', url: 'https://games.crazygames.com/en_US/narrow-one/index.html?v=1.347' },
  { name: 'Stunt Paradise', url: 'https://games.crazygames.com/en_US/stunt-paradise/index.html?v=1.347' },
  { name: 'Voxiom.io', url: 'https://games.crazygames.com/en_US/voxiom-io/index.html?v=1.347' },
  { name: 'Tileman.io', url: 'https://games.crazygames.com/en_US/tileman-io/index.html?v=1.347' },
  { name: 'Kour.io', url: 'https://games.crazygames.com/en_US/kour-io/index.html?v=1.347' },
  { name: 'Cut the Rope', url: 'https://games.crazygames.com/en_US/cut-the-rope-ebx/index.html?v=1.347' },
  { name: 'Little Alchemy', url: 'https://games.crazygames.com/en_US/little-alchemy/index.html?v=1.347' },
  { name: 'Block Blaster', url: 'https://games.crazygames.com/en_US/block-puzzle-master/index.html?v=1.347' },
  { name: 'Favorite Puzzles', url: 'https://games.crazygames.com/en_US/favorite-puzzles/index.html?v=1.347' },
  { name: 'Survev.io', url: 'https://games.crazygames.com/en_US/survev/index.html?v=1.347' },
  { name: 'Escaping the Prison', url: 'https://games.crazygames.com/en_US/escaping-the-prison/index.html?v=1.347' },
  { name: 'Squirrel with a Gun', url: 'https://games.crazygames.com/en_US/squirrel-with-a-gun/index.html?v=1.347' },
  { name: 'Eggy Car', url: 'https://games.crazygames.com/en_US/eggy-car/index.html?v=1.347' },
  { name: 'Basketball Superstars', url: 'https://games.crazygames.com/en_US/basketball-superstars/index.html?v=1.347' },
  { name: 'Shell Shockers', url: 'https://games.crazygames.com/en_US/shellshockersio/index.html?v=1.347' },
  { name: 'Agar.io', url: 'https://games.crazygames.com/en_US/agario/index.html?v=1.347' },
  { name: 'Diep.io', url: 'https://games.crazygames.com/en_US/diepio/index.html?v=1.347' },
  { name: 'Holey.io Battle Royale', url: 'https://games.crazygames.com/en_US/holey-io-battle-royale/index.html?v=1.347' },
  { name: 'LOLbeans.io', url: 'https://games.crazygames.com/en_US/lolbeans-io/index.html?v=1.347' },
  { name: 'Worms.io', url: 'https://games.crazygames.com/en_US/worms-io/index.html?v=1.347' },
  { name: 'Merge Age Warriors', url: 'https://www.crazygames.com/embed/merge-age-warriors' },
  { name: 'Jetpack Jump', url: 'https://www.crazygames.com/embed/jetpack-jump' },
  { name: 'Break the Glass', url: 'https://www.crazygames.com/embed/break-the-glass' },
  { name: 'Moto X3M', url: 'https://www.crazygames.com/embed/moto-x3m' },
  { name: 'Moto X3M 4 Winter', url: 'https://www.crazygames.com/embed/moto-x3m-4' },
  { name: 'Moto X3M 5 Pool Party', url: 'https://www.crazygames.com/embed/moto-x3m-pool-party' },
  { name: 'Disc Us', url: 'https://www.crazygames.com/embed/disc-us' },
  { name: 'Geometry Dash Meltdown', url: 'https://www.crazygames.com/embed/geometry-dash-meltdown' },
  { name: 'Geometry Dash Subzero', url: 'https://www.crazygames.com/embed/geometry-neon-dash-subzero' },
  { name: '2048', url: 'https://www.crazygames.com/embed/2048' },
  { name: 'Flow 2048 3D', url: 'https://www.crazygames.com/embed/flow-2048-3d' },
  { name: 'Clone2048', url: 'https://www.crazygames.com/embed/clone2048' },
  { name: 'Man Runner 2048', url: 'https://www.crazygames.com/embed/man-runner-2048' },
  { name: '2048 City Builder', url: 'https://www.crazygames.com/embed/2048-city-builder' },
  { name: '2048 Blocks Merge', url: 'https://www.crazygames.com/embed/2048-blocks-merge' },
  { name: 'Slither.io', url: 'https://www.crazygames.com/embed/slitherio' },
  { name: 'Mope.io', url: 'https://www.crazygames.com/embed/mopeio' },
  { name: 'Zombs Royale', url: 'https://www.crazygames.com/embed/zombsroyaleio' },
  { name: 'Paper.io 2', url: 'https://www.crazygames.com/embed/paper-io-2' },
  { name: 'Bullet Force', url: 'https://www.crazygames.com/embed/bullet-force-multiplayer' },
  { name: 'Time Shooter 3: SWAT', url: 'https://www.crazygames.com/embed/time-shooter-3-swat' },
  { name: 'Deeeep.io', url: 'https://www.crazygames.com/embed/deeeepio' },
  { name: 'Kirka.io', url: 'https://www.crazygames.com/embed/kirka-io' },
  { name: 'Wings.io', url: 'https://www.crazygames.com/embed/wingsio' },
  { name: 'Build Royale', url: 'https://www.crazygames.com/embed/buildroyale-io' },
  { name: 'Powerline.io', url: 'https://www.crazygames.com/embed/powerlineio' },
  { name: "Friday Night Funkin'", url: 'https://www.crazygames.com/embed/friday-night-funkin' },
  { name: 'Wordler', url: 'https://www.crazygames.com/embed/wordler' },
  { name: 'Splix.io', url: 'https://www.crazygames.com/embed/splixio' },
  { name: 'Superhex.io', url: 'https://www.crazygames.com/embed/superhexio' },
  { name: 'Stabfish.io', url: 'https://www.crazygames.com/embed/stabfish-io' },
  { name: 'StarBlast', url: 'https://www.crazygames.com/embed/starblastio' },
  { name: 'Snake.io', url: 'https://www.crazygames.com/embed/snake-io' },
  { name: 'Gulper.io', url: 'https://www.crazygames.com/embed/gulper-io' },
  { name: 'Sploop.io', url: 'https://www.crazygames.com/embed/sploop-io' },
  { name: 'MooMoo.io Sandbox', url: 'https://www.crazygames.com/embed/moomoo-io-sandbox' },
  { name: 'Starve.io', url: 'https://www.crazygames.com/embed/starve-io' },
  { name: 'War Brokers', url: 'https://www.crazygames.com/embed/war-brokers' },
  { name: 'Snowball.io', url: 'https://www.crazygames.com/embed/snowball-io' },
  { name: 'Hole.io', url: 'https://www.crazygames.com/embed/hole-io' },
  { name: 'Arrow.io', url: 'https://www.crazygames.com/embed/arrow-io' },
  { name: 'Aquapark.io', url: 'https://www.crazygames.com/embed/aquapark-io' },
  { name: 'Wormax.io', url: 'https://www.crazygames.com/embed/wormax-io' },
  { name: 'Drift Hunters', url: 'https://www.crazygames.com/embed/drift-hunters' },
  { name: 'Short Life', url: 'https://www.crazygames.com/embed/short-life' },
  { name: 'Short Ride', url: 'https://www.crazygames.com/embed/short-ride' },
  { name: 'Russian Car Driver ZIL 130', url: 'https://www.crazygames.com/embed/russian-car-driver-zil-130' },
  { name: 'The White Room 2', url: 'https://www.crazygames.com/embed/the-white-room-2' },
  { name: 'Riddle School 5', url: 'https://www.crazygames.com/embed/riddle-school-5' },
  { name: 'Volley Random', url: 'https://www.crazygames.com/embed/volley-random' },
  { name: 'Love Tester 3', url: 'https://www.crazygames.com/embed/love-tester-3' },
  { name: 'Fancy Pants Adventures: World 4 Part 2', url: 'https://www.crazygames.com/embed/fancy-pants-adventures-world-4-part-2' },
  { name: 'Jeff the Killer: Horrendous Smile', url: 'https://www.crazygames.com/embed/jeff-the-killer-horrendous-smile' },
]

